name: Run Tests and Save Reports

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Check Out Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libappindicator3-1 \
            fonts-liberation \
            libgbm-dev \
            libxss1 \
            xdg-utils

      # Run Maven build and tests
      - name: Build and Test with Maven
        run: mvn clean install

      # Generate Allure report (assuming Allure plugin is configured in Maven)
      - name: Generate Allure Report
        run: mvn allure:serve &

      # Upload Maven build reports (e.g., target/surefire-reports and target)
      - name: Upload Maven Reports
        uses: actions/upload-artifact@v3
        with:
          name: maven-reports
          path: |
            target/surefire-reports/   # Includes unit test results
            target/site/               # Includes site reports
            target/*.xml               # Other possible Maven reports

      # Upload Allure report (assuming the allure report is generated in the 'target/allure-results' directory)
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results/
